controller_manager:
  ros__parameters:
    update_rate: 100  # Run the control loop at 100 Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    use_urdf_to_filter: true # Automatically finds state interfaces in the URDF
    # frame_id: "base_footprint"  # Uncomment and change if your root link is named differently

position_controller:
  ros__parameters:
    joints:
      - rotor_joint